{
    "openapi": "3.0.3",
    "info": {
        "title": "KoboToolbox OpenRosa API",
        "version": "openrosa",
        "description": "Welcome to the documentation for the KoboToolbox OpenRosa API. Data collection clients, including KoboCollect and web forms, use the API endpoints described here to retrieve surveys and upload submissions.\n\nOur separate documentation of the primary KoboToolbox API endpoints, used to manage projects and data, can be found [here](/api/v2/docs/)."
    },
    "paths": {
        "/{username}/formList": {
            "get": {
                "operationId": "form_list_anonymous",
                "description": "## Implement part of the OpenRosa Form List API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as anonymous user.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "username",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form List"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/XFormList"
                                }
                            }
                        },
                        "description": null
                    }
                }
            }
        },
        "/{username}/submission": {
            "post": {
                "operationId": "submission_anonymous",
                "description": "## Implement the OpenRosa Form Submission API\n\n⚠️This endpoint is only available from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as an anonymous user.\n\n### XML Submission\n\nYou can submit an XML XForm submission using a `POST` request with `multipart/form-data`.\n\n**Example:**\n\n```bash\ncurl -X POST -F xml_submission_file=@/path/to/submission.xml \\\nhttps://kc.kobotoolbox.org/api/v1/submissions\n```\n\n### JSON Submission\n\nYou can also submit a JSON XForm submission.\n\n**Example:**\n\n```bash\ncurl -X POST -d '{\"id\": \"[form ID]\", \"submission\": [the JSON]}' \\\nhttp://localhost:8000/api/v1/submissions -H \"Content-Type: application/json\"\n```\n\nThe `[form ID]` is the `id_string` of your form, and `[the JSON]` is the submission data in JSON format.\n\n",
                "parameters": [
                    {
                        "in": "query",
                        "name": "format",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "json",
                                "xml"
                            ]
                        }
                    },
                    {
                        "in": "path",
                        "name": "username",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Submission"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/OpenRosaPayload"
                            }
                        },
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/JSONSubmissionPayload"
                            },
                            "examples": {
                                "JSONSubmission": {
                                    "value": {
                                        "id": "transportation_2011_07_25",
                                        "submission": {
                                            "transport": {
                                                "item": "bicycle",
                                                "quantity": 1
                                            },
                                            "meta": {
                                                "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390"
                                            }
                                        }
                                    },
                                    "summary": "JSON submission"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/SubmissionResponse"
                                },
                                "examples": {
                                    "JSONResponse": {
                                        "value": {
                                            "message": "Successful submission.",
                                            "formid": "transportation_2011_07_25",
                                            "encrypted": false,
                                            "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390",
                                            "submissionDate": "2023-05-24T10:00:00Z",
                                            "markedAsCompleteDate": "2023-05-24T10:00:01Z"
                                        },
                                        "summary": "JSON response"
                                    }
                                }
                            },
                            "text/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaResponse"
                                },
                                "examples": {
                                    "XMLResponse": {
                                        "value": "<OpenRosaResponse xmlns=\"http://openrosa.org/http/response\">\n    <message>Successful submission.</message>\n    <submissionMetadata xmlns=\"http://www.opendatakit.org/xforms\" id=\"transportation_2011_07_25\" instanceID=\"uuid:f3d8dc65-91a6-4d0f-9e97-802128083390\" submissionDate=\"2023-05-24T10:00:00Z\" isComplete=\"true\" markedAsCompleteDate=\"2023-05-24T10:00:01Z\"/>\n</OpenRosaResponse>",
                                        "summary": "XML response"
                                    }
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorObject"
                                },
                                "examples": {
                                    "BadRequest": {
                                        "value": {
                                            "detail": {
                                                "field_name": [
                                                    "Error message"
                                                ]
                                            }
                                        },
                                        "summary": "Bad request"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/{username}/xformsManifest/{id}": {
            "get": {
                "operationId": "manifest_anonymous",
                "description": "## Implement part of the OpenRosa Manifest API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint return the URLs of form media files so they can be fetched and displayed as needed during form rendering.\nThis endpoints will also open the form in **creation** mode and is used as an anonymous user.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "string",
                            "pattern": "^[\\d+^/]+$"
                        },
                        "required": true
                    },
                    {
                        "in": "path",
                        "name": "username",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Manifest"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaFormManifestResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/api/v2/asset_snapshots/{uid_asset_snapshot}/formList": {
            "get": {
                "operationId": "api_v2_asset_snapshots_formList_retrieve",
                "description": "## Implement part of the OpenRosa Form List API\n\nThis endpoint is used to edit the enketo submission and requires authentication\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "uid_asset_snapshot",
                        "schema": {
                            "type": "string"
                        },
                        "description": "UID of the asset snapshot",
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form List"
                ],
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "TokenAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaFormListResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "description": "No response body"
                    }
                }
            }
        },
        "/api/v2/asset_snapshots/{uid_asset_snapshot}/manifest": {
            "get": {
                "operationId": "api_v2_asset_snapshots_manifest_retrieve",
                "description": "## Implement part of the OpenRosa Form List API\n\nThis endpoint is used by Enketo when loading a form.\nIt returns the URLs of form media files so they can be fetched and displayed as\nneeded during form rendering and will open the form in edit mode.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "uid_asset_snapshot",
                        "schema": {
                            "type": "string"
                        },
                        "description": "UID of the asset snapshot",
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Manifest"
                ],
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "TokenAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaManifestResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "description": "No response body"
                    }
                }
            }
        },
        "/api/v2/asset_snapshots/{uid_asset_snapshot}/submission": {
            "post": {
                "operationId": "api_v2_asset_snapshots_submission_create",
                "description": "## Implement the OpenRosa Form Submission API\n\nThis endpoint is used only when saving edited submissions in KPI.\nNote: New submissions are still handled via the legacy v1 submission API.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "uid_asset_snapshot",
                        "schema": {
                            "type": "string"
                        },
                        "description": "UID of the asset snapshot",
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Submission"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/OpenRosaSubmissionRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "text/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaSubmissionResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotAuthenticated": {
                                        "value": {
                                            "detail": "Authentication credentials were not provided."
                                        },
                                        "summary": "Not authenticated"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/collector/{token}/formList": {
            "get": {
                "operationId": "form_list_data_collector",
                "description": "## Implement part of the OpenRosa Form List API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as a data collector.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "token",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form List"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/XFormList"
                                }
                            }
                        },
                        "description": null
                    }
                }
            }
        },
        "/collector/{token}/submission": {
            "post": {
                "operationId": "submission_data_collector",
                "description": "## Implement the OpenRosa Form Submission API\n\n⚠️This endpoint is only available from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as a data collector.\n\n### XML Submission\n\nYou can submit an XML XForm submission using a `POST` request with `multipart/form-data`.\n\n**Example:**\n\n```bash\ncurl -X POST -F xml_submission_file=@/path/to/submission.xml \\\nhttps://kc.kobotoolbox.org/api/v1/submissions\n```\n\n### JSON Submission\n\nYou can also submit a JSON XForm submission.\n\n**Example:**\n\n```bash\ncurl -X POST -d '{\"id\": \"[form ID]\", \"submission\": [the JSON]}' \\\nhttp://localhost:8000/api/v1/submissions -H \"Content-Type: application/json\"\n```\n\nThe `[form ID]` is the `id_string` of your form, and `[the JSON]` is the submission data in JSON format.\n\n",
                "parameters": [
                    {
                        "in": "query",
                        "name": "format",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "json",
                                "xml"
                            ]
                        }
                    },
                    {
                        "in": "path",
                        "name": "token",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Submission"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/OpenRosaPayload"
                            }
                        },
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/JSONSubmissionPayload"
                            },
                            "examples": {
                                "JSONSubmission": {
                                    "value": {
                                        "id": "transportation_2011_07_25",
                                        "submission": {
                                            "transport": {
                                                "item": "bicycle",
                                                "quantity": 1
                                            },
                                            "meta": {
                                                "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390"
                                            }
                                        }
                                    },
                                    "summary": "JSON submission"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/SubmissionResponse"
                                },
                                "examples": {
                                    "JSONResponse": {
                                        "value": {
                                            "message": "Successful submission.",
                                            "formid": "transportation_2011_07_25",
                                            "encrypted": false,
                                            "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390",
                                            "submissionDate": "2023-05-24T10:00:00Z",
                                            "markedAsCompleteDate": "2023-05-24T10:00:01Z"
                                        },
                                        "summary": "JSON response"
                                    }
                                }
                            },
                            "text/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaResponse"
                                },
                                "examples": {
                                    "XMLResponse": {
                                        "value": "<OpenRosaResponse xmlns=\"http://openrosa.org/http/response\">\n    <message>Successful submission.</message>\n    <submissionMetadata xmlns=\"http://www.opendatakit.org/xforms\" id=\"transportation_2011_07_25\" instanceID=\"uuid:f3d8dc65-91a6-4d0f-9e97-802128083390\" submissionDate=\"2023-05-24T10:00:00Z\" isComplete=\"true\" markedAsCompleteDate=\"2023-05-24T10:00:01Z\"/>\n</OpenRosaResponse>",
                                        "summary": "XML response"
                                    }
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorObject"
                                },
                                "examples": {
                                    "BadRequest": {
                                        "value": {
                                            "detail": {
                                                "field_name": [
                                                    "Error message"
                                                ]
                                            }
                                        },
                                        "summary": "Bad request"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/collector/{token}/xformsManifest/{id}": {
            "get": {
                "operationId": "manifest_data_collector",
                "description": "## Implement part of the OpenRosa Manifest API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint return the URLs of form media files so they can be fetched and displayed as needed during form rendering.\nThis endpoints will also open the form in **creation** mode and is used as an anonymous user.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "string",
                            "pattern": "^[\\d+^/]+$"
                        },
                        "required": true
                    },
                    {
                        "in": "path",
                        "name": "token",
                        "schema": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Manifest"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaFormManifestResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/formList": {
            "get": {
                "operationId": "form_list_authenticated",
                "description": "## Implement part of the OpenRosa Form List API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as authenticated user.\n",
                "tags": [
                    "OpenRosa Form List"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/XFormList"
                                }
                            }
                        },
                        "description": null
                    }
                }
            }
        },
        "/submission": {
            "post": {
                "operationId": "submission_authenticated",
                "description": "## Implement the OpenRosa Form Submission API\n\n⚠️This endpoint is only available from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint is used for adding submissions as an authenticated user.\n\n### XML Submission\n\nYou can submit an XML XForm submission using a `POST` request with `multipart/form-data`.\n\n**Example:**\n\n```bash\ncurl -X POST -F xml_submission_file=@/path/to/submission.xml \\\nhttps://kc.kobotoolbox.org/api/v1/submissions\n```\n\n### JSON Submission\n\nYou can also submit a JSON XForm submission.\n\n**Example:**\n\n```bash\ncurl -X POST -d '{\"id\": \"[form ID]\", \"submission\": [the JSON]}' \\\nhttp://localhost:8000/api/v1/submissions -u user:pass -H \"Content-Type: application/json\"\n```\n\nThe `[form ID]` is the `id_string` of your form, and `[the JSON]` is the submission data in JSON format.\n\n",
                "parameters": [
                    {
                        "in": "query",
                        "name": "format",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "json",
                                "xml"
                            ]
                        }
                    }
                ],
                "tags": [
                    "OpenRosa Form Submission"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/OpenRosaPayload"
                            }
                        },
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/JSONSubmissionPayload"
                            },
                            "examples": {
                                "JSONSubmission": {
                                    "value": {
                                        "id": "transportation_2011_07_25",
                                        "submission": {
                                            "transport": {
                                                "item": "bicycle",
                                                "quantity": 1
                                            },
                                            "meta": {
                                                "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390"
                                            }
                                        }
                                    },
                                    "summary": "JSON submission"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/SubmissionResponse"
                                },
                                "examples": {
                                    "JSONResponse": {
                                        "value": {
                                            "message": "Successful submission.",
                                            "formid": "transportation_2011_07_25",
                                            "encrypted": false,
                                            "instanceID": "uuid:f3d8dc65-91a6-4d0f-9e97-802128083390",
                                            "submissionDate": "2023-05-24T10:00:00Z",
                                            "markedAsCompleteDate": "2023-05-24T10:00:01Z"
                                        },
                                        "summary": "JSON response"
                                    }
                                }
                            },
                            "text/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaResponse"
                                },
                                "examples": {
                                    "XMLResponse": {
                                        "value": "<OpenRosaResponse xmlns=\"http://openrosa.org/http/response\">\n    <message>Successful submission.</message>\n    <submissionMetadata xmlns=\"http://www.opendatakit.org/xforms\" id=\"transportation_2011_07_25\" instanceID=\"uuid:f3d8dc65-91a6-4d0f-9e97-802128083390\" submissionDate=\"2023-05-24T10:00:00Z\" isComplete=\"true\" markedAsCompleteDate=\"2023-05-24T10:00:01Z\"/>\n</OpenRosaResponse>",
                                        "summary": "XML response"
                                    }
                                }
                            }
                        },
                        "description": null
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotAuthenticated": {
                                        "value": {
                                            "detail": "Authentication credentials were not provided."
                                        },
                                        "summary": "Not authenticated"
                                    }
                                }
                            }
                        },
                        "description": ""
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorObject"
                                },
                                "examples": {
                                    "BadRequest": {
                                        "value": {
                                            "detail": {
                                                "field_name": [
                                                    "Error message"
                                                ]
                                            }
                                        },
                                        "summary": "Bad request"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/xformsManifest/{id}": {
            "get": {
                "operationId": "manifest_authenticated",
                "description": "## Implement part of the OpenRosa Manifest API\n\n⚠️This endpoint is **only available** from the Kobocat domains (ex: kc.kobotoolbox.org or kc-eu.kobotoolbox.org)⚠️\n\nThis endpoint return the URLs of form media files so they can be fetched and displayed as needed during form rendering.\nThis endpoints will also open the form in **creation** mode and is used as an authenticated user.\n",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "string",
                            "pattern": "^[\\d+^/]+$"
                        },
                        "required": true
                    }
                ],
                "tags": [
                    "OpenRosa Form Manifest"
                ],
                "security": [
                    {
                        "TokenAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/OpenRosaFormManifestResponse"
                                }
                            }
                        },
                        "description": null
                    },
                    "404": {
                        "content": {
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDetail"
                                },
                                "examples": {
                                    "NotFound": {
                                        "value": {
                                            "detail": "Not found."
                                        },
                                        "summary": "Not Found"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "ErrorDetail": {
                "type": "object",
                "properties": {
                    "detail": {
                        "type": "string"
                    }
                },
                "required": [
                    "detail"
                ]
            },
            "ErrorObject": {
                "type": "object",
                "properties": {
                    "detail": {}
                },
                "required": [
                    "detail"
                ]
            },
            "JSONSubmissionPayload": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "XForm ID String"
                    },
                    "submission": {
                        "description": "The JSON submission data"
                    }
                },
                "required": [
                    "id",
                    "submission"
                ]
            },
            "OpenRosaFormListResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "formID": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "hash": {
                            "type": "string"
                        },
                        "descriptionText": {
                            "type": "string"
                        },
                        "downloadUrl": {
                            "type": "string",
                            "format": "uri",
                            "example": "https://kf.kobotoolbox.org/api/v2/asset_snapshots/{uid_asset_snapshot}/xml_with_disclaimer/"
                        },
                        "manifestUrl": {
                            "type": "string",
                            "format": "uri",
                            "example": "https://kf.kobotoolbox.org/api/v2/asset_snapshots/{uid_asset_snapshot}/manifest"
                        }
                    },
                    "xml": {
                        "name": "xform"
                    }
                },
                "xml": {
                    "name": "xforms",
                    "wrapped": true
                }
            },
            "OpenRosaFormManifestResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "filename": {
                            "type": "string"
                        },
                        "hash": {
                            "type": "string"
                        },
                        "downloadUrl": {
                            "type": "string",
                            "format": "uri",
                            "example": "https://kf.kobotoolbox.org/xformsMedia/123/456.jpg"
                        }
                    },
                    "xml": {
                        "name": "xform"
                    }
                },
                "xml": {
                    "name": "xforms",
                    "wrapped": true
                }
            },
            "OpenRosaManifestResponse": {
                "type": "object",
                "properties": {
                    "manifest": {
                        "type": "string",
                        "format": "uri",
                        "example": "https://kf.kobotoolbox.org/api/v2/asset_snapshots/{uid_asset_snapshot}/manifest"
                    }
                },
                "required": [
                    "manifest"
                ]
            },
            "OpenRosaPayload": {
                "type": "object",
                "properties": {
                    "xml_submission_file": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": [
                    "xml_submission_file"
                ]
            },
            "OpenRosaResponse": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    },
                    "submissionMetadata": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "instanceID": {
                                "type": "string"
                            },
                            "submissionDate": {
                                "type": "string",
                                "format": "date-time"
                            },
                            "markedAsCompleteDate": {
                                "type": "string",
                                "format": "date-time"
                            },
                            "isComplete": {
                                "type": "boolean"
                            }
                        }
                    }
                },
                "required": [
                    "message",
                    "submissionMetadata"
                ]
            },
            "OpenRosaSubmissionRequest": {
                "type": "object",
                "properties": {
                    "xml_submission_file": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": [
                    "xml_submission_file"
                ]
            },
            "OpenRosaSubmissionResponse": {
                "type": "object",
                "properties": {
                    "question": {
                        "type": "string"
                    },
                    "meta": {
                        "type": "object",
                        "properties": {
                            "instanceID": {
                                "type": "string"
                            },
                            "rootUuid": {
                                "type": "string"
                            },
                            "deprecatedID": {
                                "type": "string"
                            }
                        }
                    },
                    "formhub": {
                        "type": "object",
                        "properties": {
                            "uuid": {
                                "type": "string"
                            }
                        }
                    }
                },
                "required": [
                    "formhub",
                    "meta",
                    "question"
                ]
            },
            "SubmissionResponse": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    },
                    "formid": {
                        "type": "string"
                    },
                    "encrypted": {
                        "type": "boolean"
                    },
                    "instanceID": {
                        "type": "string"
                    },
                    "submissionDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "markedAsCompleteDate": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "required": [
                    "encrypted",
                    "formid",
                    "instanceID",
                    "markedAsCompleteDate",
                    "message",
                    "submissionDate"
                ]
            },
            "XFormList": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "formID": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "majorMinorVersion": {
                            "type": "string"
                        },
                        "version": {
                            "type": "string"
                        },
                        "hash": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "downloadUrl": {
                            "type": "string",
                            "format": "uri",
                            "example": "https://kf.kobotoolbox.org/forms/6/form.xml"
                        },
                        "manifestUrl": {
                            "type": "string",
                            "format": "uri",
                            "example": "https://kf.kobotoolbox.org/xformsManifest/6"
                        }
                    },
                    "xml": {
                        "name": "xform"
                    }
                },
                "xml": {
                    "name": "xforms",
                    "wrapped": true
                }
            }
        },
        "securitySchemes": {
            "BasicAuth": {
                "type": "http",
                "scheme": "basic"
            },
            "TokenAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Token-based authentication. Use the format: `Token <your-token>`"
            }
        }
    }
}